all:
	python3 ../bin/svalint.py -t test_sva_missing_label_f.sv
	python3 ../bin/svalint.py -t test_sva_missing_label_p.sv
	python3 ../bin/svalint.py -t test_sva_pass_ablk_f.sv
	python3 ../bin/svalint.py -t test_21_f.sv
	python3 ../bin/svalint.py -t test_21_p.sv
	python3 ../bin/svalint.py -t test_33_f.sv
	python3 ../bin/svalint.py -t test_33_f_full.sv
	python3 ../bin/svalint.py -t test_29_f.sv
	python3 ../bin/svalint.py -t test_30_f.sv
	python3 ../bin/svalint.py -t test_38_f.sv
	python3 ../bin/svalint.py -t test_40_f.sv
